global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'unibank-gateway'
    static_configs:
      - targets: ['gateway:5000']
    metrics_path: '/metrics'

  - job_name: 'unibank-admin'
    static_configs:
      - targets: ['admin:5010']
    metrics_path: '/metrics'

  - job_name: 'unibank-core'
    static_configs:
      - targets: ['core:5020']
    metrics_path: '/metrics'

  - job_name: 'unibank-switching'
    static_configs:
      - targets: ['switching:5030']
    metrics_path: '/metrics'

  - job_name: 'unibank-terminal-manager'
    static_configs:
      - targets: ['terminal-manager:5040']
    metrics_path: '/metrics'

  - job_name: 'unibank-hsm'
    static_configs:
      - targets: ['hsm:5050']
    metrics_path: '/metrics'

  - job_name: 'unibank-reporting'
    static_configs:
      - targets: ['reporting:5060']
    metrics_path: '/metrics'

  - job_name: 'unibank-notifications'
    static_configs:
      - targets: ['notifications:5070']
    metrics_path: '/metrics'
