global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'goldbank-gateway'
    static_configs:
      - targets: ['gateway:1112']
    metrics_path: '/metrics'

  - job_name: 'goldbank-admin'
    static_configs:
      - targets: ['admin:5010']
    metrics_path: '/metrics'

  - job_name: 'goldbank-terminal-manager'
    static_configs:
      - targets: ['terminal-manager:5004']
    metrics_path: '/metrics'

  - job_name: 'goldbank-hsm'
    static_configs:
      - targets: ['hsm:5005']
    metrics_path: '/metrics'

  - job_name: 'goldbank-notifications'
    static_configs:
      - targets: ['notifications:5007']
    metrics_path: '/metrics'

  - job_name: 'synergy-switch'
    static_configs:
      - targets: ['switch:8080']
    metrics_path: '/metrics'
