using GoldBank.SharedKernel.Domain;

namespace GoldBank.Core.Modules.Ekub.Domain.Entities;

/// <summary>
/// Records the bank's monthly product fee being debited from a group's pot.
/// One row per (group, period). Generated by the ApplyMonthlyFee handler — for
/// v1 invoked manually (admin / cron); group ledger reads sum these rows as
/// negative entries against the pot.
/// </summary>
public sealed class EkubFee : AggregateRoot
{
    public Guid GroupId { get; set; }
    public string Period { get; set; } = default!;       // "YYYY-MM"
    public decimal Amount { get; set; }
    public string Currency { get; set; } = default!;
    public string TenantId { get; set; } = default!;
}
